### PR TITLE
Bug: removed SpringDoc apiLicenseUrl and apiExternalDocUrl blank value

### LINKED ISSUE #10262: SpringDoc external URL and licence URL should not be blank
`SpringdocModuleFactory` set `apiLicenseUrl` and `apiExternalDocUrl` to blank which is not valid and will cauyse parsing problem (ex: to use with OpenApi diff).

Either need to remove this properties from the template or valuated them

### PR DESCRIPTION
**Pull request by richersoon**
Close #10262

### CODE REVIEW

File: src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoccore/domain/SpringdocModuleFactory.java [hunk 1]
```diff
@@ -42,9 +42,7 @@ private JHipsterModule buildModule(JHipsterModuleProperties properties, SpringDo
         .put("apiTitle", "Project API")
         .put("apiDescription", "Project description API")
         .put("apiLicenseName", "No license")
-        .put("apiLicenseUrl", "")
```
Comment (DamnClin) [inline src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoccore/domain/SpringdocModuleFactory.java:45]: Also needs to be removed from the template

**Review by DamnClin — APPROVED** [review]

File: src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoccore/domain/SpringdocModuleFactory.java (hunk 1 above)
Comment (richersoon) [reply src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoccore/domain/SpringdocModuleFactory.java:45]: Hi @DamnClin , I already just removed them from the template. Please check again.

Comment (DamnClin) [reply src/main/java/tech/jhipster/lite/generator/server/springboot/apidocumentation/springdoccore/domain/SpringdocModuleFactory.java:45]: Yep, thanks, LGTM :)
