### PR TITLE
bug: missing eslint-config-prettier configuration in eslint.config.js

### LINKED ISSUE #12124: bug: missing eslint-config-prettier configuration in eslint.config.js
For both react and vue, eslint-config-prettier is not configured, which leads to conflict between prettier and eslint.

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #12124

### CODE REVIEW

**Review by murdos — CHANGES_REQUESTED** [review]
Actually the typescript module doesn't depend on prettier, so it's not really fair to add eslint-config-prettier here.
Furthermore eslint-config-prettier recommends to add prettier config in last position.

**Comment by qmonmert** [comment]
@murdos we add ESLint in TypescriptModuleFactory, so I don't think that we must add eslint-config-prettier in PrettierModuleFactory ... WDYT?

**Comment by murdos** [comment]
> @murdos we add ESLint in TypescriptModuleFactory, so I don't think that we must add eslint-config-prettier in PrettierModuleFactory ... WDYT?

My first thought was to add `eslint-config-prettier` dependency (and config) in react and vue modules, since they both require typescript and prettier.

But indeed that would not work if you just apply `prettier` and `typescript` module: the conflict between both tools will exist.

I'm tempted to keep the addition of eslint-config-prettier in PrettierModuleFactory like you did, but to also make `typescript` depends on `prettier`. That would resolve the case. WDYT?
In that case we would be able to remove the dependency to prettier from vue and react.

File: src/main/java/tech/jhipster/lite/generator/typescript/core/domain/TypescriptModuleFactory.java [hunk 1]
```diff
@@ -62,7 +58,18 @@ public JHipsterModule buildModule(JHipsterModuleProperties properties) {
           .addTemplate("eslint.config.js")
           .and()
         .and()
+      .apply(patchEslintConfigPrettier())
```
Comment (murdos) [inline src/main/java/tech/jhipster/lite/generator/typescript/core/domain/TypescriptModuleFactory.java:61]: You can just update the template `eslint.config.js` that is added a few lines above (l. 58), this would be much simpler :)

**Comment by qmonmert** [comment]
> > @murdos we add ESLint in TypescriptModuleFactory, so I don't think that we must add eslint-config-prettier in PrettierModuleFactory ... WDYT?
> 
> My first thought was to add `eslint-config-prettier` dependency (and config) in react and vue modules, since they both require typescript and prettier.
> 
> But indeed that would not work if you just apply `prettier` and `typescript` module: the conflict between both tools will exist.
> 
> I'm tempted to keep the addition of eslint-config-prettier in PrettierModuleFactory like you did, but to also make `typescript` depends on `prettier`. That would resolve the case. WDYT? In that case we would be able to remove the dependency to prettier from vue and react.

I agree to add a dependency between Typescript and Prettier.
To resume: if I add Prettier (with eslint-config-prettier), I need Typescript (with eslint) before.
Ok for you?

File: src/main/java/tech/jhipster/lite/generator/prettier/infrastructure/primary/PrettierModuleConfiguration.java [hunk 2]
```diff
@@ -19,7 +18,7 @@ JHipsterModuleResource prettierModule(PrettierApplicationService prettier) {
       .slug(PRETTIER)
       .propertiesDefinition(initPropertiesDefinition())
       .apiDoc("Prettier", "Format project with prettier")
-      .organization(JHipsterModuleOrganization.builder().addDependency(INIT).build())
+      .organization(JHipsterModuleOrganization.builder().addDependency(INIT).addDependency(TYPESCRIPT).build())
```
Comment (murdos) [inline src/main/java/tech/jhipster/lite/generator/prettier/infrastructure/primary/PrettierModuleConfiguration.java:21]: Sorry, I was maybe not clear: it's the other way: Typescript module should depends on Prettier.

Comment (qmonmert) [reply src/main/java/tech/jhipster/lite/generator/prettier/infrastructure/primary/PrettierModuleConfiguration.java:21]: 😕 and eslint-config-prettier is added in TypescriptModuleFactory or PrettierModuleFactory ?

Comment (murdos) [reply src/main/java/tech/jhipster/lite/generator/prettier/infrastructure/primary/PrettierModuleConfiguration.java:21]: Eslint-config-prettier is added by the typescript module (because it adds eslint).

**Review by murdos — APPROVED** [review]

**Comment by murdos** [comment]
Thanks @qmonmert !

**Comment by pascalgrimaud** [comment]
Adding a bounty for all your last PRs, @qmonmert 
thanks for your work

**Comment by qmonmert** [comment]
@pascalgrimaud thanks https://opencollective.com/generator-jhipster/expenses/243647

**Comment by pascalgrimaud** [comment]
@qmonmert : approved
