### PR TITLE
Bug: templatize application name in ApplicationErrorsHandlerTest.java…

### LINKED ISSUE #10503: Fix ApplicationErrorsHandlerTest.java.mustache
In `ApplicationErrorsHandlerTest.java.mustache` There is two hardcoded "Fullapp" name for a test which will totally fail on generated application named anything else than Fullapp, should be templatized

### PR DESCRIPTION
**Pull request by richersoon**
Close #10503

### CODE REVIEW

File: src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationErrorsHandlerTest.java.mustache [hunk 1]
```diff
@@ -24,7 +24,7 @@ class {{ baseName }}ErrorsHandlerTest {
 
   @Test
   void shouldLogServerErrorAsError() {
-    handler.handleFullappException(FullappException.internalServerError(StandardErrorKey.INTERNAL_SERVER_ERROR).message("Oops").build());
+    handler.handle{{ baseName }}Exception({{ baseName }}Exception.internalServerError(StandardErrorKey.INTERNAL_SERVER_ERROR).message("Oops").build());
```
Comment (murdos) [inline src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationErrorsHandlerTest.java.mustache:27]: Could you add an assertion in the corresponding unit test to verify that the generated content matches the expectation?

Comment (richersoon) [reply src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationErrorsHandlerTest.java.mustache:27]: @murdos I think already it already have  assertion on the line number 29, but if it is not enough, please give me example or reference what kind of test needed? Thanks

Comment (richersoon) [reply src/main/resources/generator/server/springboot/mvc/internationalized-errors/test/ApplicationErrorsHandlerTest.java.mustache:27]: @murdos @DamnClin , I already added assertion in `InternationalizedErrorsModuleFactoryTest`, please check

**Review by murdos — APPROVED** [review]
