### PR TITLE
Use CucumberJpaReset instead of JpaBeersReseter

### LINKED ISSUE #3102: Use CucumberJpaReset instead of JpaBeersReseter
A lot of build are failing because of flaky (I guess) Cucumber tests. See [this build](https://github.com/jhipster/jhipster-lite/runs/7849481560?check_suite_focus=true#step:9:3583) for instance.

On dummy feature, we use 2 different methods for wiping data, they are concurrent. We should only use one.

### PR DESCRIPTION
**Pull request by hdurix**
Fix #3102

### CODE REVIEW

File: src/main/resources/generator/server/springboot/cucumber/CucumberJpaReset.java.mustache [hunk 1]
```diff
@@ -1,24 +1,19 @@
...
-import org.springframework.beans.factory.annotation.Autowired;
-import org.springframework.data.jpa.repository.JpaRepository;
-
 import io.cucumber.java.After;
 import io.cucumber.java.Before;
+import java.util.Collection;
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.data.jpa.repository.JpaRepository;
 
 public class CucumberJpaReset {
```
Comment (DamnClin) [inline src/main/resources/generator/server/springboot/cucumber/CucumberJpaReset.java.mustache:9]: Transactional annotation should be in template instead of being added in modules

File: src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactory.java [hunk 2]
```diff
@@ -20,6 +20,10 @@ public class DummyJpaPersistenceModuleFactory {
 
   private static final TextNeedleBeforeReplacer IMPORT_NEEDLE = lineBeforeText("import org.springframework.stereotype.Service;");
 
+  private static final TextNeedleBeforeReplacer CUCUMBER_IMPORT_NEEDLE = lineBeforeText(
```
Comment (DamnClin) [inline src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactory.java:23]: All cucumber related information should be removed from here

File: src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactoryTest.java [hunk 3]
```diff
@@ -23,7 +23,7 @@ void shouldBuildModule() {
 
     JHipsterModule module = factory.buildModule(properties);
 
-    assertThatModuleWithFiles(module, beersApplicationService(), dummyInMemoryRepository(), inMemoryBeersReseter())
+    assertThatModuleWithFiles(module, beersApplicationService(), dummyInMemoryRepository(), inMemoryBeersReseter(), cucumberReseter())
```
Comment (DamnClin) [inline src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactoryTest.java:26]: This module should not do anything on JPA reset files

File: src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactory.java [hunk 4]
```diff
@@ -68,6 +76,12 @@ public JHipsterModule buildModule(JHipsterModuleProperties properties) {
             .add(CREATE_METHOD_NEEDLE, spaces + "@Transactional")
           .and()
         .and()
+        .optionalReplacements()
```
Comment (DamnClin) [inline src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactory.java:79]: This module should have a dependency to `springboot-cucumber-jpa-reset` instead

File: src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactory.java (hunk 2 above)
Comment (hdurix) [reply src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactory.java]: done

File: src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactoryTest.java (hunk 3 above)
Comment (hdurix) [reply src/test/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactoryTest.java]: changed

File: src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactory.java (hunk 4 above)
Comment (hdurix) [reply src/main/java/tech/jhipster/lite/generator/server/springboot/mvc/dummy/jpapersistence/domain/DummyJpaPersistenceModuleFactory.java]: added

**Review by DamnClin — APPROVED** [review]
