### PR TITLE
Bug: added check if repository is null in CucumberJpaReset

### LINKED ISSUE #10097: Cucumber JPA reset should not fail without repository
CucumberJpaReset fails when there is no declared repository, should be updated to:

```java
public class CucumberJpaReset {

  @Autowired(required = false)
  private Collection<JpaRepository<?, ?>> repositories;

  @After
  @Before
  @Transactional
  public void wipeData() {
    if (repositories == null) {
      return;
    }

    repositories.forEach(JpaRepository::deleteAllInBatch);
  }
}
```

### PR DESCRIPTION
**Pull request by richersoon**
Close #10097

### CODE REVIEW

File: src/main/resources/generator/server/springboot/cucumber/CucumberJpaReset.java.mustache [hunk 1]
```diff
@@ -18,6 +18,10 @@ public class CucumberJpaReset {
   @Before
   @Transactional
   public void wipeData() {
+    if (repositories == null) {
```
Comment (DamnClin) [inline src/main/resources/generator/server/springboot/cucumber/CucumberJpaReset.java.mustache:21]: Not sure that will be enough without de required false on the repositories injection

Comment (richersoon) [reply src/main/resources/generator/server/springboot/cucumber/CucumberJpaReset.java.mustache:22]: I've also added the required false on repositories injection, please check @DamnClin . thanks

**Review by DamnClin — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
Thanks for your contribution @richersoon
