### PR TITLE
move module endpoints (get + post /apply-patch)

### LINKED ISSUE #3276: Dynamic module urls don't use exception handler
Dynamic module urls (handled in `JHipsterModuleApplicationController`) do not use the application exception handler (and it should)

### PR DESCRIPTION
**Pull request by AnneJacquet**
closes #3276

### CODE REVIEW

File: src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java [hunk 1]
```diff
@@ -48,4 +57,23 @@ public ResponseEntity<RestJHipsterLandscape> modulesLandscape() {
   public void applyPatches(@RequestBody @Validated RestJHipsterModulesToApply modulesToApply) {
     modules.apply(modulesToApply.toDomain(projectFolder));
   }
+
+  @PostMapping("modules/{slug}/apply-patch")
+  public void applyPatch(@RequestBody @Validated RestJHipsterModuleProperties restProperties, @PathVariable("slug") String slug) {
```
Comment (DamnClin) [inline src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:62]: I remember now that I had to do the dynamic stuff to handle legacy URLs. An attention point: I think the swagger documentation for this is not OK now. I think we should keep the dynamic documentation and not document this endpoint

File: src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java [hunk 2]
```diff
@@ -48,4 +57,23 @@ public ResponseEntity<RestJHipsterLandscape> modulesLandscape() {
...
+    if (!modulesMap.containsKey(slug)) {
+      throw InvalidModuleQueryException.unknownModule(slug);
+    }
+    JHipsterModuleProperties properties = restProperties.toDomain(projectFolder);
+    JHipsterModuleResource module = modulesMap.get(slug);
+    modules.apply(new JHipsterModuleToApply(module.slug(), module.factory().create(properties)));
+  }
+
+  @GetMapping("modules/{slug}")
+  public RestJHipsterModulePropertiesDefinition propertiesDefinition(@PathVariable("slug") String slug) {
```
Comment (DamnClin) [inline src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:72]: Same as previous endpoint

**Review by DamnClin — CHANGES_REQUESTED** [review]

File: src/test/java/tech/jhipster/lite/module/infrastructure/secondary/TestJHipsterModules.java [hunk 3]
```diff
@@ -20,31 +21,33 @@ public final class TestJHipsterModules {
...
-    private static JHipsterModulesApplicationService buildApplicationService() {
+    private static JHipsterModulesApplicationService buildApplicationService(JHipsterModule module) {
       ProjectFilesReader filesReader = new FileSystemProjectFilesReader();
 
       FileSystemJHipsterModulesRepository modulesRepository = new FileSystemJHipsterModulesRepository(
         filesReader,
         NpmVersionsFixture.npmVersions(filesReader),
         mock(JavaProjects.class),
-        JHipsterModulesResourceFixture.moduleResources()
+        new JHipsterModulesResources(List.of(defaultModuleResourceBuilder().slug("test-module").factory(properties -> module).build()))
```
Comment (AnneJacquet) [inline src/test/java/tech/jhipster/lite/module/infrastructure/secondary/TestJHipsterModules.java:50]: Had to change the test as only the slug and the properties and needed to apply module. And the module is fetch with its slug from the list. So the list is no longer static in the test but only contains 1 module each time : the one we're trying to apply.

File: src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java [hunk 4]
```diff
@@ -43,10 +43,18 @@ public Stream<JHipsterModuleResource> stream() {
     return resources.values().stream();
   }
 
+  public JHipsterModuleResource get(JHipsterModuleSlug slug) {
```
[the remark this answers is not in the document]
Comment (DamnClin) [reply src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java:46]: This logic can't be in the resource. This is a business responsibility, must be in the domain

File: src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java (hunk 1 above)
Comment (DamnClin) [reply src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:58]: Yep, we just need to be sure that this endpoint is ignored in swagger

File: src/test/java/tech/jhipster/lite/module/infrastructure/primary/ModulesSteps.java [hunk 5]
```diff
@@ -1,8 +1,9 @@
 package tech.jhipster.lite.module.infrastructure.primary;
 
-import static org.assertj.core.api.Assertions.*;
-import static tech.jhipster.lite.TestProjects.*;
-import static tech.jhipster.lite.cucumber.CucumberAssertions.*;
+import static org.assertj.core.api.Assertions.assertThat;
```
Comment (DamnClin) [inline src/test/java/tech/jhipster/lite/module/infrastructure/primary/ModulesSteps.java:3]: Update your static imports policy to have * starting at 1

File: src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (DamnClin) [reply src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java:46]: Oh my bad! I'll take a closer look at that tomorrow, sorry

[the remark this answers is not in the document]
Comment (AnneJacquet) [reply src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java:46]: Ok great, no problem, thought I was missing something !

[the remark this answers is not in the document]
Comment (DamnClin) [reply src/main/java/tech/jhipster/lite/module/domain/resource/JHipsterModulesResources.java:46]: Ok, great!

I'll go with: 

```java
  public JHipsterModuleResource get(JHipsterModuleSlug slug) {
    assertKnownSlug(slug);
    
    return resources.get(slug);
  }

  private void assertKnownSlug(JHipsterModuleSlug slug) {
    Assert.notNull("slug", slug);
    
    if (!resources.containsKey(slug)) {
      throw new UnknownSlugException(slug);
    }
  }
```

File: src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java [hunk 6]
```diff
@@ -32,20 +36,35 @@ public ModulesResource(JHipsterModulesApplicationService modules, ProjectFolder
   }
 
   @GetMapping("/modules")
+  @Tag(name = "Modules")
```
Comment (DamnClin) [inline src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:39]: annotation order: shortest ones comes first

File: src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java [hunk 7]
```diff
@@ -32,20 +36,35 @@ public ModulesResource(JHipsterModulesApplicationService modules, ProjectFolder
...
   @Operation(summary = "List available modules")
   public ResponseEntity<RestJHipsterModules> listModules() {
     return ResponseEntity.ok(modulesList);
   }
 
   @GetMapping("modules-landscape")
+  @Tag(name = "Modules")
```
Comment (DamnClin) [inline src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:46]: annotation order: shortest ones comes first

File: src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java [hunk 8]
```diff
@@ -32,20 +36,35 @@ public ModulesResource(JHipsterModulesApplicationService modules, ProjectFolder
...
   @Operation(summary = "Get a view of the current modules landscape")
   public ResponseEntity<RestJHipsterLandscape> modulesLandscape() {
     return ResponseEntity.ok(modulesLandscape);
   }
 
   @PostMapping("apply-patches")
+  @Tag(name = "Modules")
```
Comment (DamnClin) [inline src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:53]: annotation order: shortest ones comes first

File: src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java (hunk 1 above)
Comment (DamnClin) [reply src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:60]: This is shown in swagger and it's really important that it don't show since there are better documentation for each modules

Comment (AnneJacquet) [reply src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:60]: I looked too quickly, I thought removing the @Tag from the controller worked 🤦‍♀️ Done !

File: src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java [hunk 9]
```diff
@@ -48,4 +54,18 @@ public ResponseEntity<RestJHipsterLandscape> modulesLandscape() {
...
   }
+
+  @Hidden
+  @PostMapping("modules/{slug}/apply-patch")
+  public void applyPatch(@RequestBody @Validated RestJHipsterModuleProperties restProperties, @PathVariable("slug") String slug) {
+    JHipsterModuleProperties properties = restProperties.toDomain(projectFolder);
+    modules.apply(new JHipsterModuleToApply(new JHipsterModuleSlug(slug), properties));
+  }
+
+  @Hidden
```
Comment (DamnClin) [inline src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:65]: This one should not be hidden I think since there is nothing specific by module

Comment (AnneJacquet) [reply src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:65]: I don't know if we're talking about the same thing but there are 2 endpoints per module on the swagger ui
image

Comment (DamnClin) [reply src/main/java/tech/jhipster/lite/module/infrastructure/primary/ModulesResource.java:65]: Oh true, I though that was the apply all endpoint... I should stop doing reviews on my phone...

**Review by DamnClin — APPROVED** [review]

**Comment by DamnClin** [comment]
Thanks for your work here @AnneJacquet , don't forget to claim for the $300 for this :)

**Comment by AnneJacquet** [comment]
Claimed https://opencollective.com/generator-jhipster/expenses/102135 :)

**Comment by pascalgrimaud** [comment]
@AnneJacquet : approved, thanks for your work :-)
