### PR TITLE
fix DB drivers and Devtools dependency declaration

### LINKED ISSUE #4154: Fix dependency declaration for DB drivers and Devtools
Should be 
```
<dependency>
	<groupId>org.postgresql</groupId>
	<artifactId>postgresql</artifactId>
	<scope>runtime</scope>
</dependency>
``` 
and 
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-devtools</artifactId>
	<scope>runtime</scope>
	<optional>true</optional>
</dependency>
```

### PR DESCRIPTION
**Pull request by biergit**
Fix #4154

### CODE REVIEW

File: src/main/java/tech/jhipster/lite/generator/server/springboot/database/mssql/domain/MsSQLModuleFactory.java [hunk 1]
```diff
@@ -38,7 +39,8 @@ public JHipsterModule buildModule(JHipsterModuleProperties properties) {
         )
         .and()
       .javaDependencies()
-        .addDependency(groupId("com.microsoft.sqlserver"), artifactId("mssql-jdbc"))
+        .addDependency(javaDependency().groupId("com.microsoft.sqlserver").artifactId("mssql-jdbc").scope(
+          JavaDependencyScope.RUNTIME).build())
```
Comment (pascalgrimaud) [inline src/main/java/tech/jhipster/lite/generator/server/springboot/database/mssql/domain/MsSQLModuleFactory.java:43]:
```suggestion
        .addDependency(javaDependency().groupId("com.microsoft.sqlserver").artifactId("mssql-jdbc").scope(JavaDependencyScope.RUNTIME).build())
```

**Review by pascalgrimaud — APPROVED** [review]

**Review by pascalgrimaud — APPROVED** [review]
